name: Lint workflows

on:
  workflow_dispatch:
  pull_request:
    paths:
      - '.github/workflows/*.yml'
      - '.github/workflows/*.yaml'

permissions:
  contents: read

# This allows a subsequently queued workflow run to interrupt previous runs
concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  lint-workflows:
    runs-on: ubuntu-latest
    timeout-minutes: 2
    steps:
      - name: Check out repo
        uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846

      - name: Run linter
        uses: cschleiden/actions-linter@caffd707beda4fc6083926a3dff48444bc7c24aa
        with:
          # ".github/workflows/scorecards-analysis.yml" is an exception as `on: branch_protection_rule` is not recognized yet
          workflows: '[".github/workflows/*.yml", ".github/workflows/*.yaml", "!.github/workflows/scorecards-analysis.yml"]'
